name: buku_kecilku
description: Aplikasi notebook untuk menulis ide

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher" # Nama icon yang dihasilkan di Android
  ios: true # Aktifkan untuk iOS
  image_path: "assets/icon/logo_app.png" # Sesuaikan dengan path gambar Anda
  min_sdk_android: 21 # Opsional, tapi disarankan untuk mendukung Android modern